3 modifica competenze
plansoft-it/GestioneCompetenze pull request #11
Opened 2020-11-06 14:36 UTC by Leomorga

2020-11-07 14:18 UTC, KernelPanic92 commented on edit.js
> +    document.getElementById("employee").innerHTML+='<option value='+i+'>'+dipendenti[i].nome+'</option>'
```suggestion
    const { nome } = dipendenti[i];
    document.getElementById("employee").innerHTML+=`<option value="${i}"> ${ nome } </option>`
```

2020-11-07 14:19 UTC, KernelPanic92 commented on edit.js
> +function showSkillnoArea(){
serve?

2020-11-07 14:20 UTC, KernelPanic92 commented on edit.js
> +    var employee=document.getElementById("employee").value
```suggestion
    const employee=document.getElementById("employee").value
```

2020-11-07 14:26 UTC, KernelPanic92 commented on edit.js
> +    for(let i=0;i<dipendenti[employee].competenzeAssociate.length;i++){
illeggibile... tirati fuori la variabile competenze associate

```suggestion
    const competenze = dipendenti[employee].competenzeAssociate;
    for(let i=0; i < competenze.length; i++) {
```

2020-11-07 14:27 UTC, KernelPanic92 commented on edit.js
> +    for(let i=0;i<dipendenti[employee].competenzeAssociate.length;i++){
e ricordati di mettere gli spazi di formattazione, per noi esseri umani si legge molto meglio, per le macchine esistono i minificatori

2020-11-07 14:31 UTC, KernelPanic92 commented on addSkill.html
> +                <td><input type="text" name="nomeSkill" id="nomeSkill" placeholder="nuova competenza"></td>
scrivo qui ma vale per tutta la pull request

ok che siamo italiani, parliamo italiano e ci aspettiamo il sito web con le label italiane, però la lingua franca per programmare è l'inglese quindi tutto ciò che è programmazione o modellazione (html) deve riportare nomi in inglese

2020-11-07 14:35 UTC, KernelPanic92 commented on edit.js
> +        console.log(dipendenti)
rimuovere

2020-11-07 14:37 UTC, KernelPanic92 commented on edit.js
> +var dipendenti=[
const?

2020-11-07 14:37 UTC, KernelPanic92 commented on edit.js
> +var tempLivelli=['base', 'intermedio', 'avanzato']
const? spazi?

2020-11-07 14:37 UTC, KernelPanic92 commented on edit.js
> +for(let i=0;i<dipendenti.length;i++){
spazi

2020-11-10 08:42 UTC, Wabri commented on edit.js
> +for(let i=0;i<dipendenti.length;i++){
Per spazi si intende formattazione

2020-11-10 09:36 UTC, scrivereleonardo commented on edit.js
> +        console.log(dipendenti)
Ma un controllo extra non può far comodo?

2020-11-10 10:17 UTC, KernelPanic92 requested changes

2020-11-10 10:17 UTC, KernelPanic92 commented on edit.js
> +    document.getElementById("employee").innerHTML+=`<option value="${i}"> ${ name } </option>`
spazietti e semicolon sono importanti

```suggestion
    document.getElementById("employee").innerHTML += `<option value="${i}"> ${ name } </option>`;
```

2020-12-10 08:41 UTC, merged