Realizzazione entità Dipendente
plansoft-it/GestioneCompetenze pull request #25
Opened 2020-12-11 16:22 UTC by mate94

entità Dipendente cosituita dai campi:
id, nome e cognome.
Sono compresi anche il controller, service e repository per la gestione
della suddetta entità

2020-12-11 16:25 UTC, mate94 commented
Non so perché questo commit non è stato associato alla issue #15, potresti darci un'occhiata?

2020-12-15 09:59 UTC, Wabri requested changes
La formattazione è importante, ricordati di scrivere anche per gli altri non solo per te.

2020-12-15 09:59 UTC, Wabri commented on src/main/java/plansoft/gestionecompetenze/dipendente/Dipendente.java
> +public class Dipendente {
Nonostante la nostra lingua madre sia l'italiano, dobbiamo cercare di scrivere il codice in lingua inglese.

Dipendenti = Employees

2020-12-15 09:59 UTC, Wabri commented on src/main/java/plansoft/gestionecompetenze/dipendente/Dipendente.java
> +	private String nome;
Stessa cosa vale per i campi => nome = name

2020-12-15 09:59 UTC, Wabri commented on src/main/java/plansoft/gestionecompetenze/dipendente/Dipendente.java
> +	private String cognome;
Vedi commento sopra

2020-12-15 09:59 UTC, Wabri commented on src/main/java/plansoft/gestionecompetenze/dipendente/DipendenteController.java
> +	@RequestMapping("/dipendenti")
Anche qui e soprattutto qui la mappatura dell'endpoint deve essere in inglese

2020-12-15 09:59 UTC, Wabri commented on src/main/java/plansoft/gestionecompetenze/dipendente/DipendenteController.java
> +	@RequestMapping("/dipendenti/{id}")
Vedi commento sopra

2020-12-15 09:59 UTC, Wabri commented on src/main/java/plansoft/gestionecompetenze/dipendente/DipendenteController.java
> +	@RequestMapping(method = RequestMethod.POST, value="/dipendenti")
Vedi commento sopra

2020-12-15 09:59 UTC, Wabri commented on src/main/java/plansoft/gestionecompetenze/dipendente/DipendenteController.java
> +	@RequestMapping(method= RequestMethod.PUT, value="/dipendenti/{id}")
Vedi commento sopra

2020-12-15 09:59 UTC, Wabri commented on src/main/java/plansoft/gestionecompetenze/dipendente/DipendenteController.java
> +	@RequestMapping(method = RequestMethod.DELETE, value= "/dipendenti/{id}")
Vedi commento sopra

2020-12-15 16:20 UTC, Wabri requested changes
A parte qualche disallineamento di formattazione e alcune classi che hanno mantenuto la traduzione in italiano, va tutto bene.

2020-12-15 16:20 UTC, Wabri commented on src/main/java/plansoft/skillsmanagement/dipendente/Dipendente.java
> +	}
Ci vuole una riga vuota tra un metodo e l'altro

2020-12-15 16:20 UTC, Wabri commented on src/main/java/plansoft/skillsmanagement/dipendente/Dipendente.java
> +	}
Come sopra

2020-12-15 16:20 UTC, Wabri commented on src/main/java/plansoft/skillsmanagement/dipendente/Dipendente.java
> +	}
Come sopra

2020-12-15 16:20 UTC, Wabri commented on src/main/java/plansoft/skillsmanagement/dipendente/Dipendente.java
> +	}
Come sopra

2020-12-15 16:20 UTC, Wabri commented on src/main/java/plansoft/skillsmanagement/dipendente/Dipendente.java
> +	}
Come sopra

2020-12-15 16:20 UTC, Wabri commented on src/main/java/plansoft/skillsmanagement/dipendente/Dipendente.java
> +	}
Come sopra

2020-12-15 16:20 UTC, Wabri commented on src/main/java/plansoft/skillsmanagement/dipendente/Dipendente.java
> +	}
Come sopra

2020-12-15 16:20 UTC, Wabri commented on src/main/java/plansoft/skillsmanagement/dipendente/DipendenteController.java
> +public class DipendenteController {
Duplicato di EmployeeController quindi lo puoi togliere

Ma non li avevamo eliminati?

2020-12-15 16:20 UTC, Wabri commented on src/main/java/plansoft/skillsmanagement/dipendente/DipendenteRepository.java
> +public interface DipendenteRepository extends CrudRepository<Dipendente, String>{
Duplicato di EmployeeRepository quindi lo puoi togliere

Ma non li avevamo eliminati?

2020-12-15 16:20 UTC, Wabri commented on src/main/java/plansoft/skillsmanagement/dipendente/DipendenteService.java
> +public class DipendenteService {
Duplicato di EmployeeService quindi lo puoi togliere

Ma non li avevamo eliminati?

2020-12-16 16:10 UTC, LORYMAX4 reviewed
Eliminato file derby.log. Per il resto tutto ok.

2020-12-16 16:14 UTC, merged