WIP: 12 documentazione
plansoft-it/GestioneCompetenze pull request #27
Opened 2020-12-15 13:11 UTC by Wabri

Closes #12

2020-12-16 08:16 UTC, Leomorga requested changes

2020-12-16 08:16 UTC, Leomorga commented on README.md
> +Ad ogni dipendente è associato: nome, cognome , un id identificativo e una lista di competenze con associato il livello della suddetta competenza.
Non è citata l'area, occhio agli spazi

2020-12-16 08:16 UTC, Leomorga commented on README.md
> +E' stato utilizzato per il prototipo per il progetto, per fare una parte delle  delle pagine in maniera statica. Inoltre viene utilizzato anche nella versione 1.0.0 zero del progetto, sempre con lo s
C'è uno zero di troppo?

2020-12-16 08:16 UTC, Leomorga commented on README.md
> +CSS è stato utilizzato, e continuerà nel corso del progetto come foglio di stile del progetto, per "abbellire" le pagine.
un sinonimo di abbellire? magari "stilizzare" e riformuli prima?

2020-12-16 08:16 UTC, Leomorga commented on README.md
> +Per poter insallare e iniziare a lavorare su angular è necessario installare [Node.js](https://nodejs.org/en/) , preferibilmente l'ultima versione stabile (LTS), è inoltre necessario l'"npm package m
Ricontrolla questa riga e togli i doppi apici e gli spazi di troppo

2020-12-16 08:16 UTC, Leomorga commented on README.md
> +Anche JS, come HTML , è stato utilizzato per fare la prima bozza del del progetto. Verrà poi rimpiazzato con Typescript in mondo da poter lavorare con angular un maniera ottimale.
Occhio agli spazi

2020-12-16 08:16 UTC, Leomorga commented on README.md
> +Per la documentazione o per trovare informazioni riguardanti il sudetto linguaggio, visita [questo sito](https://developer.mozilla.org/en-US/docs/Web/JavaScript)
"suddetto"

2020-12-16 08:16 UTC, Leomorga commented on README.md
> +La versione di  Angular adoprata è la 11.
"adottata" forse suona meglio, occhio agli spazi

2020-12-16 08:16 UTC, Leomorga commented on README.md
> +In fine , dopo questi passaggi puoi aprire la console di comando e scrivere `npm install -g @angular/cli` per effettuare l'installazione di Angular
Gli spazi >:(

2020-12-16 08:16 UTC, Leomorga commented on README.md
> +Viene richiesta la creazione di un portale per le gestione delle competenze dei dipendenti di PS. Tramite questo portale si avrà la possibilità di effettuare:
"la" gestione

2020-12-16 08:18 UTC, Wabri commented on README.md
> +In fine , dopo questi passaggi puoi aprire la console di comando e scrivere `npm install -g @angular/cli` per effettuare l'installazione di Angular
E attento anche ai doppi apici

2020-12-16 13:00 UTC, Leomorga commented on README.md
> +In fine , dopo questi passaggi puoi aprire la console di comando e scrivere `npm install -g @angular/cli` per effettuare l'installazione di Angular
Infine attaccato?

2020-12-16 13:05 UTC, scrivereleonardo commented on README.md
> +Ad ogni dipendente è associato: nome, cognome , un id identificativo e una lista di competenze con associato il livello della suddetta competenza.
Aggiungo l' area, la spaziatura della virgola va bene così.

2020-12-16 13:07 UTC, scrivereleonardo commented on README.md
> +Per poter insallare e iniziare a lavorare su angular è necessario installare [Node.js](https://nodejs.org/en/) , preferibilmente l'ultima versione stabile (LTS), è inoltre necessario l'"npm package m
Rimossi i doppi apici

2020-12-17 08:27 UTC, Leomorga requested changes

2020-12-17 08:27 UTC, Leomorga commented on README.md
> +Ad ogni dipendente è associato: nome, cognome, un id identificativo e una lista di competenze con associato il livello della suddetta competenza.
ancora non citi da nessuna parte l'area di competenza

2020-12-17 08:27 UTC, Leomorga commented on README.md
> +E' stato utilizzato per il prototipo per il progetto, per fare una parte delle  delle pagine in maniera statica. Inoltre viene utilizzato anche nella versione 1.0.0  del progetto, sempre con lo stess
"delle delle" occhio

2020-12-17 08:27 UTC, Leomorga commented on README.md
> +Anche JS, come HTML, è stato utilizzato per fare la prima bozza del del progetto. Verrà poi rimpiazzato con Typescript in mondo da poter lavorare con angular un maniera ottimale.
"del del" occhio

2020-12-17 08:27 UTC, Leomorga commented on README.md
> +CSS è utilizzato nel corso dello sviluppo come foglio di stile del progetto, ha la funzione di stilizzare le pagine.
Forse possiamo riformulare la frase per non avere la ripetizione di stile, ma è marginale

2020-12-17 08:27 UTC, Leomorga commented on README.md
> +La versione di  Angular adottata è la 11.
occhio qui al doppio spazio tra di e Angular

2020-12-17 08:27 UTC, Leomorga commented on README.md
> +Per poter installare e iniziare a lavorare su angular è necessario installare [Node.js](https://nodejs.org/en/), preferibilmente l'ultima versione stabile (LTS), è inoltre necessario l'npm package ma
"aprila la console" occhio

2020-12-17 08:27 UTC, Leomorga commented on README.md
> +Infin, dopo questi passaggi puoi aprire la console di comando e scrivere `npm install -g @angular/cli` per effettuare l'installazione di Angular
"Infin" occhio

2020-12-17 09:17 UTC, Wabri commented on README.md
> +Anche JS, come HTML, è stato utilizzato per fare la prima bozza del del progetto. Verrà poi rimpiazzato con Typescript in mondo da poter lavorare con angular un maniera ottimale.
```suggestion
Anche JS, come HTML, è stato utilizzato per fare la prima bozza del progetto. Verrà poi rimpiazzato con Typescript in mondo da poter lavorare con angular un maniera ottimale. 
```

2020-12-17 09:17 UTC, Wabri commented on README.md
> +E' stato utilizzato per il prototipo per il progetto, per fare una parte delle  delle pagine in maniera statica. Inoltre viene utilizzato anche nella versione 1.0.0  del progetto, sempre con lo stess
```suggestion
E' stato utilizzato per il prototipo per il progetto, per fare una parte delle pagine in maniera statica. Inoltre viene utilizzato anche nella versione 1.0.0  del progetto, sempre con lo stesso scopo ma in maniera differente
```

2020-12-17 09:17 UTC, Wabri commented on README.md
> +La versione di  Angular adottata è la 11.
```suggestion
La versione di Angular adottata è la 11.
```

2020-12-17 09:18 UTC, Wabri commented on README.md
> +Per poter installare e iniziare a lavorare su angular è necessario installare [Node.js](https://nodejs.org/en/), preferibilmente l'ultima versione stabile (LTS), è inoltre necessario l'npm package ma
```suggestion
Per poter installare e iniziare a lavorare su angular è necessario installare [Node.js](https://nodejs.org/en/), preferibilmente l'ultima versione stabile (LTS), è inoltre necessario l'npm package manager, che dovrebbe comunque essere installato insieme a Node.js, per controllare se sul tuo computer è installato il client apri la la console (cmd) e scrivi `npm -v`, qualora ci fossero problemi, visita il [sito ufficiale di npm](https://docs.npmjs.com/about-npm)
```

2020-12-17 09:18 UTC, Wabri commented on README.md
> +Infin, dopo questi passaggi puoi aprire la console di comando e scrivere `npm install -g @angular/cli` per effettuare l'installazione di Angular
```suggestion
Infine, dopo questi passaggi puoi aprire la console di comando e scrivere `npm install -g @angular/cli` per effettuare l'installazione di Angular
```

2020-12-17 11:34 UTC, scrivereleonardo commented on README.md
> +Infin, dopo questi passaggi puoi aprire la console di comando e scrivere `npm install -g @angular/cli` per effettuare l'installazione di Angular
E' molto poetico Infin , quasi quasi lo lascio 
(Scherzo)

2020-12-17 13:54 UTC, Leomorga requested changes

2020-12-17 13:54 UTC, Leomorga commented on README.md
> +Ad ogni dipendente è associato: nome, cognome, un id identificativo e una lista di competenze con associata ad ognuna l'area tecnica di cui fa parte , e il livello di conoscenza della specifica compe
```suggestion
Ad ogni dipendente è associato: nome, cognome, un id identificativo e una lista di competenze con associata ad ognuna l'area tecnica di cui fa parte, e il livello di conoscenza della specifica competenza.
```

2020-12-17 13:54 UTC, Leomorga commented on README.md
> +E' stato utilizzato per il prototipo per il progetto, per fare una parte  delle pagine in maniera statica. Inoltre viene utilizzato anche nella versione 1.0.0  del progetto, sempre con lo stesso scop
```suggestion
E' stato utilizzato per il prototipo per il progetto, per fare una parte delle pagine in maniera statica. Inoltre viene utilizzato anche nella versione 1.0.0 del progetto, sempre con lo stesso scopo ma in maniera differente
```

2020-12-18 08:21 UTC, merged