14Realizzazione entità Level
plansoft-it/GestioneCompetenze pull request #31
Opened 2020-12-15 14:55 UTC by mate94

La realizzazione dell'entità Level comprende:
-classe Level (con campi id e description)
-classe LevelController
-classe LevelService
-interfaccia LevelRepository

Closes#14

2020-12-15 16:22 UTC, Wabri requested changes
Va tutto bene, fatta eccezione per la formattazione

2020-12-15 16:22 UTC, Wabri commented on src/main/java/plansoft/skillsmanagement/level/Level.java
> +	}
Ricordati della formattazione

2020-12-15 16:22 UTC, Wabri commented on src/main/java/plansoft/skillsmanagement/level/Level.java
> +	}
Ricordati della formattazione

2020-12-15 16:22 UTC, Wabri commented on src/main/java/plansoft/skillsmanagement/level/Level.java
> +	}
Ricordati della formattazione

2020-12-15 16:22 UTC, Wabri commented on src/main/java/plansoft/skillsmanagement/level/Level.java
> +	}
Ricordati della formattazione

2020-12-15 16:22 UTC, Wabri commented on src/main/java/plansoft/skillsmanagement/level/Level.java
> +	}
Ricordati della formattazione

2020-12-15 16:22 UTC, Wabri commented on src/main/java/plansoft/skillsmanagement/level/LevelService.java
> +		.forEach(levels::add);
Mi piacerebbe di più con almeno un tab in più

2020-12-16 16:14 UTC, LORYMAX4 approved these changes

2020-12-16 16:25 UTC, LORYMAX4 commented on src/main/java/plansoft/skillsmanagement/level/Level.java
> +	private String id;
Tipo variabile int.

2020-12-16 16:27 UTC, LORYMAX4 commented on src/main/java/plansoft/skillsmanagement/level/Level.java
> +	public Level(String id, String description) {
Tipo variabile int.

2020-12-16 16:27 UTC, LORYMAX4 commented on src/main/java/plansoft/skillsmanagement/level/Level.java
> +	public String getId() {
Tipo variabile int

2020-12-16 16:27 UTC, LORYMAX4 commented on src/main/java/plansoft/skillsmanagement/level/Level.java
> +	public void setId(String id) {
Tipo variabile int.

2020-12-16 16:28 UTC, LORYMAX4 commented on src/main/java/plansoft/skillsmanagement/level/LevelController.java
> +	public Optional<Level> getLevel(@PathVariable String id) {
Tipo variabile int.

2020-12-16 16:28 UTC, LORYMAX4 commented on src/main/java/plansoft/skillsmanagement/level/LevelController.java
> +	public void updateLevel(@RequestBody Level level, @PathVariable String id) {
Come sopra.

2020-12-16 16:29 UTC, LORYMAX4 commented on src/main/java/plansoft/skillsmanagement/level/LevelController.java
> +	public void deleteLevel(@PathVariable String id) {
Come sopra.

2020-12-16 16:30 UTC, LORYMAX4 commented on src/main/java/plansoft/skillsmanagement/level/LevelRepository.java
> +public interface LevelRepository extends CrudRepository<Level, String> {
Tipo variabile int.

2020-12-16 16:30 UTC, LORYMAX4 commented on src/main/java/plansoft/skillsmanagement/level/LevelService.java
> +	public Optional<Level> getLevel(String id) {
Tipo variabile int.

2020-12-16 16:30 UTC, LORYMAX4 commented on src/main/java/plansoft/skillsmanagement/level/LevelService.java
> +	public void updateLevel(Level level, String id) {
Come sopra.

2020-12-16 16:31 UTC, LORYMAX4 commented on src/main/java/plansoft/skillsmanagement/level/LevelService.java
> +	public void deleteLevel(String id) {
Come sopra.

2020-12-16 16:31 UTC, LORYMAX4 reviewed
Campo id di tipo int.

2020-12-17 08:21 UTC, LORYMAX4 approved these changes
Tutto ok.

2020-12-17 09:16 UTC, merged