Realizzazione dell'entità SkillEmp effettuata
plansoft-it/GestioneCompetenze pull request #38
Opened 2020-12-23 11:00 UTC by mate94

Essa comprende la realizzazione di tutte le classi utili alla gestione della suddetta entità:
controller, service, repository ed entità

Closes #23

2020-12-23 12:01 UTC, Wabri requested changes
Riguardare i nomi in generale, cercare di essere il più chiaro possibile, pensare sempre a chi deve leggere il nostro codice.

emp = https://en.wikipedia.org/wiki/Electromagnetic_pulse

2020-12-23 12:01 UTC, Wabri commented on src/main/java/plansoft/skillsmanagement/skillemp/SkillEmpService.java
> +	public void updateSkillEmpLevel(int id_lev,int id_emp, int id_skill) {
Camel case

2020-12-24 09:17 UTC, LORYMAX4 commented on src/main/java/plansoft/skillsmanagement/skillemployee/SkillEmployee.java
> +	private int idemployee;
Camel case

2020-12-24 09:20 UTC, LORYMAX4 commented on src/main/java/plansoft/skillsmanagement/skillemployee/SkillEmployee.java
> +	private int idskill;
Camel case

2020-12-24 09:20 UTC, LORYMAX4 commented on src/main/java/plansoft/skillsmanagement/skillemployee/SkillEmployee.java
> +	private int idlevel;
Camel case

2020-12-24 09:25 UTC, LORYMAX4 commented on src/main/java/plansoft/skillsmanagement/skillemployee/SkillEmployeeRepository.java
> +	List<SkillEmployee> findAllByIdskill(int idskill);
Camel case

2020-12-24 09:26 UTC, LORYMAX4 commented on src/main/java/plansoft/skillsmanagement/skillemployee/SkillEmployeeRepository.java
> +	List<SkillEmployee> findAllByIdemployee(int id_emp);
Vedi sopra

2020-12-24 09:26 UTC, LORYMAX4 commented on src/main/java/plansoft/skillsmanagement/skillemployee/SkillEmployeeRepository.java
> +	void deleteByIdemployee(int id_emp);
Vedi sopra

2020-12-24 09:32 UTC, LORYMAX4 requested changes
Camel case da rivedere

2020-12-24 10:57 UTC, LORYMAX4 approved these changes

2020-12-28 14:26 UTC, Wabri approved these changes

2020-12-28 14:26 UTC, merged