20 ricerca
plansoft-it/GestioneCompetenze pull request #41
Opened 2021-01-07 11:02 UTC by scrivereleonardo

Closes #20 #17

2021-01-07 15:01 UTC, Wabri requested changes
- [ ] il package-lock.json non è necessario perchè viene ricreato ogni volte che viene eseguita una build ng quindi puoi eliminarlo, quello importante è il package.json in cui ci sono tutte le configurazioni del progetto

2021-01-07 15:14 UTC, scrivereleonardo commented on Angular/GestioneCompetenze/.browserslistrc
> +# This file is used by the build system to adjust CSS and JS output to support the specified browsers below.
Intendi che posso proprio cancellare il file browserlistrc?

2021-01-11 13:46 UTC, Wabri commented on Angular/GestioneCompetenze/.browserslistrc
> +# This file is used by the build system to adjust CSS and JS output to support the specified browsers below.
Si

2021-04-07 07:56 UTC, Wabri approved these changes

2021-04-07 07:56 UTC, merged