Aggiunti file per "Mostrare Lista Competenze Utenti"
plansoft-it/GestioneCompetenze pull request #9
Opened 2020-11-06 11:14 UTC by scrivereleonardo

Closes #2 

Aggiunta pagina che ha la funzione di stampare TUTTI gli utenti all'avvio della pagina.

showCompetences.js, all' interno del quale c'è il codice Javascript per la stampa di ogni singolo utente e le comptense annesse

 ShowAllUserPage.html , che mostra mostra a schermo tutti gli utenti, elencati uno sopra l'altro

2020-11-06 13:55 UTC, Wabri requested changes
Qualche imprecisione da correggere nello script e da formattare meglio togliendo gli spazi vuoi e linee commentate, ma complessivamente è ok.

2020-11-06 13:55 UTC, Wabri commented on showCompetences.js
> +// let users = [
Elimina i commenti inutili

2020-11-06 13:55 UTC, Wabri commented on showCompetences.js
> +    for (let index = 0; index < users.length; index++) {
La formattazione è importante

2020-11-06 13:55 UTC, Wabri commented on showCompetences.js
> +// let spaceShowUsers= document.getElementById("show");
Elimina i commenti inutili

2020-11-06 13:55 UTC, Wabri commented on showCompetences.js
> +        document.getElementById("show").innerHTML += "<ul><br><li> Nome e Cognome: " + users[index].userName + "</li><br> <li> Competenze: <br> " + printArrayOfObject(users[index].competenceUser) + "
Sarebbe visivamente più comodo avere la stringa su più linee:

https://dev-tips.com/javascript/multi-line-strings-in-javascript

2020-11-06 13:55 UTC, Wabri commented on showCompetences.js
> +        output += "<br>  <ul><li>Competenza Conosciuta: "+arrOfobj[index].nameComp + "</li><li>   AreaCompetenza: "+arrOfobj[index].area+ "</li><li> Livello Competenza:"+arrOfobj[index].level+ "</ul>
Sarebbe visivamente più comodo avere la stringa su più linee:

https://dev-tips.com/javascript/multi-line-strings-in-javascript

2020-11-06 19:26 UTC, KernelPanic92 commented on showCompetences.js
> +for (let index = 0; index < users.length; index++) {
Usa il "for of" tanto l'indice non lo usi:

for (const user of users) {
  // Something
}

2020-11-06 19:37 UTC, KernelPanic92 commented on showCompetences.js
> +    document.getElementById("show").innerHTML += "<ul>\
Secondo me se lo formatti meglio vedi di più se hai gestito bene le chiusure dei tag...  prova con il backtic:
document.getElementById("show").innerHTML += `
  <ul>
    <br>
    <li> Nome e Cognome: ${user.userName} </li>
    <br>
    <li> 
         Competenze:
         <br>
         ${printArrayOfObject(usercompetenceUser)}
 </ul>
 <br>
 <br>
 <hr>
`;

@Wabri

2020-11-06 19:39 UTC, KernelPanic92 commented on showCompetences.js
> +    for (let index = 0; index < arrOfobj.length; index++) {
Come sopra

2020-11-06 19:39 UTC, KernelPanic92 commented on showCompetences.js
> +        output += "<br><ul>\
Come sopra x backtic

2020-11-06 19:41 UTC, KernelPanic92 commented on showCompetences.js
> +    var output = "";
`let`

2020-11-06 19:42 UTC, KernelPanic92 commented on showCompetences.js
> +function clear(space) {
Userei un nome più parlante per il parametro ad esempio "element"

2020-11-09 16:48 UTC, KernelPanic92 requested changes

2020-11-09 16:48 UTC, KernelPanic92 commented on showCompetences.js
> +            <li> Competenze:
tag mai chiuso

2020-11-09 16:48 UTC, KernelPanic92 commented on showCompetences.js
> +            <li> Nome e Cognome: ` + user.userName + `</li><br>
il backtick è ganzo proprio perché puoi usare le string template

```suggestion
            <li> Nome e Cognome: ${ user.userName } </li><br>
```

2020-11-09 16:48 UTC, KernelPanic92 commented on showCompetences.js
> +            <br>` + printArrayOfObject(user.competenceUser) +`
come sopra

2020-11-09 16:48 UTC, KernelPanic92 commented on showCompetences.js
> +                <li>Competenza Conosciuta: `+competence.nameComp + `</li>
come sopra

2020-11-09 16:48 UTC, KernelPanic92 commented on showCompetences.js
> +        <ul><br>
manca il self closing su br, rivedilo un po' ovunque

2020-11-09 16:48 UTC, KernelPanic92 commented on ShowAllUserPage.html
> +<!DOCTYPE html>
si può includere uno screen della funzionalità?

2020-11-09 16:48 UTC, KernelPanic92 commented on styles.css
> +.greenStandardButton{
spazietti, ricontrolla anche le altre classi

2020-11-09 16:48 UTC, KernelPanic92 commented on styles.css
> +    background-color: blue;
ma unnnnn'era green? @Wabri

2020-11-09 16:49 UTC, KernelPanic92 commented on showCompetences.js
> +        userName: "Mario Rossi",
o usi i doppi apici o usi i singoli apici.... comunque sia sarebbe sempre meglio usare gli apici singoli per le stringhe js.... riguarda un po' a tappeto tutto

2020-11-09 16:51 UTC, KernelPanic92 commented on styles.css
> +    background-color: blue;
ps. spazio 😡

2020-12-10 09:01 UTC, Wabri commented on styles.css
> +    background-color: blue;
A me lo chiedi?

2020-12-10 09:13 UTC, merged